/** Phường/Xã (mới, sau sáp nhập 7/2025) -> Quận/Huyện CŨ tương ứng — bảng tra cứu hành chính tĩnh
 * (theo Nghị quyết 1685/NQ-UBTVQH15), dùng để gộp dữ liệu theo Phường (đã có sẵn) lên cấp Quận/Huyện
 * cho bản đồ (public/geo/hcm-districts.geojson). Không phụ thuộc dữ liệu đơn hàng — luôn phủ đủ
 * 102 phường của TP.HCM cũ. Nguồn: D:\Claude CODE\web\vung-phu-map\scripts\ward_crosswalk.py. */
export const WARD_TO_DISTRICT: Record<string, string> = {
  "Bến Thành": "Quận 1",
  "Tân Định": "Quận 1",
  "Sài Gòn": "Quận 1",
  "Cầu Ông Lãnh": "Quận 1",
  "Bàn Cờ": "Quận 3",
  "Nhiêu Lộc": "Quận 3",
  "Xuân Hòa": "Quận 3",
  "Hòa Bình": "Quận 3",
  "Vĩnh Hội": "Quận 4",
  "Khánh Hội": "Quận 4",
  "Xóm Chiếu": "Quận 4",
  "Bình Đông": "Quận 8",
  "Chợ Quán": "Quận 5",
  "An Đông": "Quận 5",
  "Chợ Lớn": "Quận 5",
  "Diên Hồng": "Quận 10",
  "Bình Tiên": "Quận 6",
  "Bình Tây": "Quận 6",
  "Bình Phú": "Quận 6",
  "Phú Lâm": "Quận 6",
  "Tân Mỹ": "Quận 7",
  "Tân Hưng": "Quận 7",
  "Tân Thuận": "Quận 7",
  "Phú Thuận": "Quận 7",
  "Chánh Hưng": "Quận 8",
  "Phú Định": "Quận 8",
  "Vườn Lài": "Quận 10",
  "Hòa Hưng": "Quận 10",
  "Phú Thọ": "Quận 11",
  "Bình Thới": "Quận 11",
  "Minh Phụng": "Quận 11",
  "Đông Hưng Thuận": "Quận 12",
  "Trung Mỹ Tây": "Quận 12",
  "Tân Thới Hiệp": "Quận 12",
  "Thới An": "Quận 12",
  "An Phú Đông": "Quận 12",
  "Gia Định": "Quận Bình Thạnh",
  "Bình Thạnh": "Quận Bình Thạnh",
  "Bình Lợi Trung": "Quận Bình Thạnh",
  "Thạnh Mỹ Tây": "Quận Bình Thạnh",
  "Bình Quới": "Quận Bình Thạnh",
  "Bình Tân": "Quận Bình Tân",
  "Bình Hưng Hòa": "Quận Bình Tân",
  "Bình Trị Đông": "Quận Bình Tân",
  "An Lạc": "Quận Bình Tân",
  "Tân Tạo": "Quận Bình Tân",
  "Hạnh Thông": "Quận Gò Vấp",
  "An Nhơn": "Quận Gò Vấp",
  "Gò Vấp": "Quận Gò Vấp",
  "Thông Tây Hội": "Quận Gò Vấp",
  "An Hội Tây": "Quận Gò Vấp",
  "An Hội Đông": "Quận Gò Vấp",
  "Đức Nhuận": "Quận Phú Nhuận",
  "Cầu Kiệu": "Quận Phú Nhuận",
  "Phú Nhuận": "Quận Phú Nhuận",
  "Tân Sơn Hòa": "Quận Tân Bình",
  "Tân Sơn Nhất": "Quận Tân Bình",
  "Tân Hòa": "Quận Tân Bình",
  "Bảy Hiền": "Quận Tân Bình",
  "Tân Bình": "Quận Tân Bình",
  "Tân Sơn": "Quận Tân Bình",
  "Tây Thạnh": "Quận Tân Phú",
  "Tân Sơn Nhì": "Quận Tân Phú",
  "Phú Thọ Hòa": "Quận Tân Phú",
  "Phú Thạnh": "Quận Tân Phú",
  "Tân Phú": "Quận Tân Phú",
  "Vĩnh Lộc": "Huyện Bình Chánh",
  "Tân Vĩnh Lộc": "Huyện Bình Chánh",
  "Bình Lợi": "Huyện Bình Chánh",
  "Tân Nhựt": "Huyện Bình Chánh",
  "Bình Chánh": "Huyện Bình Chánh",
  "Hưng Long": "Huyện Bình Chánh",
  "Bình Hưng": "Huyện Bình Chánh",
  "An Nhơn Tây": "Huyện Củ Chi",
  "Thái Mỹ": "Huyện Củ Chi",
  "Nhuận Đức": "Huyện Củ Chi",
  "Tân An Hội": "Huyện Củ Chi",
  "Củ Chi": "Huyện Củ Chi",
  "Phú Hòa Đông": "Huyện Củ Chi",
  "Bình Mỹ": "Huyện Củ Chi",
  "Bình Khánh": "Huyện Cần Giờ",
  "Cần Giờ": "Huyện Cần Giờ",
  "An Thới Đông": "Huyện Cần Giờ",
  "Thạnh An": "Huyện Cần Giờ",
  "Hóc Môn": "Huyện Hóc Môn",
  "Bà Điểm": "Huyện Hóc Môn",
  "Xuân Thới Sơn": "Huyện Hóc Môn",
  "Đông Thạnh": "Huyện Hóc Môn",
  "Nhà Bè": "Huyện Nhà Bè",
  "Hiệp Phước": "Huyện Nhà Bè",
  "Hiệp Bình": "Thành Phố Thủ Đức",
  "Tam Bình": "Thành Phố Thủ Đức",
  "Thủ Đức": "Thành Phố Thủ Đức",
  "Linh Xuân": "Thành Phố Thủ Đức",
  "Long Bình": "Thành Phố Thủ Đức",
  "Tăng Nhơn Phú": "Thành Phố Thủ Đức",
  "Phước Long": "Thành Phố Thủ Đức",
  "Long Phước": "Thành Phố Thủ Đức",
  "Long Trường": "Thành Phố Thủ Đức",
  "An Khánh": "Thành Phố Thủ Đức",
  "Bình Trưng": "Thành Phố Thủ Đức",
  "Cát Lái": "Thành Phố Thủ Đức",
};
